export const SAMPLE_CONSTANT = 'SAMPLE_CONSTANT';
export const APP_THEME = 'APP_THEME';
export const USER_SIGNUP_START = 'USER_SIGNUP_START'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
